### ISSUE TITLE
Combining of CSS rules breaks when using browser prefixes and selectors

### ISSUE THREAD

**Issue by BradMclain** [google/closure-stylesheets#109]
For example the following:
```css
.search [type="search"]::-webkit-input-placeholder {
  color: rgba(255, 255, 255, 0.4);
}
.search [type="search"]::-moz-placeholder {
  color: rgba(255, 255, 255, 0.4);
}
.search [type="search"]:-ms-input-placeholder {
  color: rgba(255, 255, 255, 0.4);
}
.search [type="search"]::placeholder {
  color: rgba(255, 255, 255, 0.4);
}
```

Will be rewritten as:
```css
.search [type="search"]::-webkit-input-placeholder,.search [type="search"]::-moz-placeholder,.search [type="search"]:-ms-input-placeholder,.search [type="search"]::placeholder{
  color:rgba(255,255,255,0.4)
}
```

However standard browser behaviour is to ignore a rule if any selector in a group of selectors is not recognised or is invalid. In this case the browser prefixes will always fail in other browsers so this rule is never applied.

See https://www.w3.org/TR/css3-selectors/#Conformance which has the line:
```
a group of selectors containing an invalid selector is invalid.
```
