### ISSUE TITLE
Parsing error with CSS vars

### ISSUE THREAD

**Issue by oliverfernandez** [google/closure-stylesheets#116]
closure-stylesheets is throwing a parsing error when a CSS file uses [CSS3 variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)

For example, the following file
````css
:root {
--color: red;
}

div {
 background-color: var(--color);
}
````

throws

```
Compiler parsing error: Parse error in test.css at line 2 column 1:
--color: red;
^
```

Is there any quick solution to prevent this, or a change in closure-stylesheets is necessary?
