### ISSUE TITLE
Improper Parsing of Unicode

### ISSUE THREAD

**Issue by iflan** [google/closure-stylesheets#50]
Originally reported on Google Code with ID 31
```
What steps will reproduce the problem?
When a string contains a unicode character specification, it does not parse properly.
Specifically, it works when it is 6 digits long, but not if it is less.

This works:

.rule:after { content: " \00203a "; }

This breaks:

.rule:after { content: " \203a "; }


This should be allowed according to the CSS2 spec:

http://www.w3.org/TR/CSS2/syndata.html#characters

```

Reported by `mankoff@google.com` on 2013-03-15 15:13:13

**Comment by iflan** [comment]
This is fixed.

```css
.arule:after { content: " \00203a "; }

.brule:after { content: " \203a "; }
```

produces:

```css
.arule:after, .brule:after {
  content: " \203a";
}
```
