### ISSUE TITLE
Feature Request: Suppress @component prefixing

### ISSUE THREAD

**Issue by SLaks** [google/closure-stylesheets#73]
There are many cases where I want to style a component-prefixed class iff it's contained within a different, non-component-prefixed class.  Currently, this requires that you drop the component entirely.

Proposed syntax:

```css
@component "blah" {
  .^GlobalState .%LocalState {
    color: red;
  }
}
```

Output:

```css
.GlobalState .BlahLocalState {
  color: red;
}
```

I use `^` since it's after `%` on the keyboard, and to match regex conventions (signifying that this is the actual beginning of the classname).

Open question: In `.^A .B`, should `.B` be prefixed? I think not, for consistency.
