### ISSUE TITLE
Source maps still aren't produced correctly

### ISSUE THREAD

**Issue by iflan** [google/closure-stylesheets#95]
Even after fixing #11, it's clear that source maps aren't being generated correctly.

Given:
```css
@def BG_COLOR red;

.test {
  font-family: Helvetica, Tahoma;
  background-color: BG_COLOR;
}
```

The compiler produces:
```css
.a{font-family:Helvetica,Tahoma;background-color:red}
```
and the sourcemap:
```json
{
"version":3,
"file":"test.source.map",
"lineCount":1,
"mappings":"AAEqB,CAAD,CAGwE,aAFjD,QAAA,CAAA,CAAW,KAAX,CAEiD,kBAL9E;",
"sources":["/tmp/test.gss"],
"names":[]
}
```

A [visualization] of the sourcemap shows that the `@def` is correctly linked, but none of the other parts make much sense.

[visualization]: https://sokra.github.io/source-map-visualization/#base64,LmF7Zm9udC1mYW1pbHk6SGVsdmV0aWNhLFRhaG9tYTtiYWNrZ3JvdW5kLWNvbG9yOnJlZH0=,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGVzdC5zb3VyY2UubWFwIiwibGluZUNvdW50IjoxLCJtYXBwaW5ncyI6IkFBRXFCLENBQUQsQ0FHd0UsYUFGakQsUUFBQSxDQUFBLENBQVcsS0FBWCxDQUVpRCxrQkFMOUU7Iiwic291cmNlcyI6WyIvdG1wL3Rlc3QuZ3NzIl0sIm5hbWVzIjpbXX0=,QGRlZiBCR19DT0xPUiByZWQ7CgoudGVzdCB7CiAgZm9udC1mYW1pbHk6IEhlbHZldGljYSwgVGFob21hOwogIGJhY2tncm91bmQtY29sb3I6IEJHX0NPTE9SOwp9
